baseurl: "https://welcomerain.pub"
metaDataFormat: "yaml"
title: "Welcome Rain"
theme: "blist"
DefaultContentLanguage: "en"
DefaultContentLanguageInSubdir: true
canonifyURLs: false
#disqusShortname: "welcomerain"
services:
  googleAnalytics:
    ID: G-SB346R14Y2
languages:
  en:
    contentDir: "content/en" #English
    disabled: false
    weight: 1
    languageName: "English"
    params:
      introTitle: "Welcome Rain"
      introSubtitle: "Enhancing Health, Wealth, & Relationships — A Journey of Empowerment"
      introPhoto: "/leavesgreen.jpg"
      logo: "/base_icon_transparent_background.png"
      thumbnail: "/wlr_link_m_bio.png"
    menu:
      main:
        - name: "Home"
          url: "/"
          weight: 1
        - name: "Blog"
          url: "blog"
          weight: 2
        - name: "Top Post"
          url: "/en/blog/elfred/"
          weight: 3
        - name: "About"
          url: "page/about/"
          weight: 4
        - name: "Tags"
          url: "tags"
          weight: 5
        - name: "Privacy Policy"
          url: "page/privacy-policy"
          weight: 6
  de:
    contentDir: "content/de" # Deutsch
    disabled: true
    weight: 2
    languageName: "Deutsch"
    title: "Blist (mehrsprachig)"
    params:
      introTitle: "Welcome Rain"
      introSubtitle: "26-jährige Junior-Entwicklerin, die Spaß an sozialen Kartenspielen, Bloggen und Malen hat"
      introPhoto: "/picture.png"
      logo: "/new.png"
    menu:
      main:
        - name: "Home"
          url: "/"
        - name: "Blog"
          url: "blog"
          weight: 1
        - name: "Über mich"
          url: "page/about/"
          weight: 2
        - name: "Tags"
          url: "tags"
          weight: 3
  fr:
    contentDir: "content/fr" #French
    disabled: true
    weight: 1
    languageName: "Français"
    params:
      introTitle: "Welcome Rain"
      introSubtitle: "Développeuse junior de 26 ans qui adore les jeux de société, le blogging et la peinture"
      introPhoto: "/picture.png"
      logo: "/new.png"
    menu:
      main:
        - name: "Blog"
          url: "blog"
          weight: 1
        - name: "À propos"
          url: "page/about/"
          weight: 2
        - name: "Tags"
          url: "tags"
          weight: 3
  dy:
    contentDir: "content/dy" #Example language
    disabled: true
    weight: 3
    languageName: "Test Language"
outputs:
  home:
    - HTML
    - RSS
    - JSON
params:
  defaultTheme: "dark"
  darkModeToggle: true
  enableSearch: true
  social:
    twitter: welcomerainpub
  description: Text about my cool site
  images:
    - base_icon_transparent_background.png
  searchKeys: ["tags", "date", "categories", "summary", "content", "link", "author"]
  copyright: "Copyright © 2024 - Welcome Rain · All rights reserved"
  favicon: "/black_icon_transparent_background.png"
  ascentColor: "bg-blue-100"
  frontBundle: "blog"
  hideMeta: false
  hideOtherLanguages: true
  toc: true
  hidePageThumbnail: false
  comments:
    system: "giscus"
    repo: "anitguru/hugo"
    repoid: "R_kgDOK4q08w"
    category: "General"
    categoryid: "DIC_kwDOK4q0884Cbxq3"
    mapping: "title"
    strict: "0"
    reactionsenabled: "1"
    emitmetadata: "0"
    inputposition: "top"
    theme: "preferred_color_scheme"
  homepage:
    social:
      title: "Follow Us"
      description: "Stay Updated, Stay Inspired: Don't miss out on our latest insights and stories—join the community! ⚡🌟"
      icons:
        - website: "tiktok"
          url: "https://wlr.link/tiktok"
        - website: "pinterest"
          url: "https://wlr.link/pinterest"
        - website: "twitter"
          url: "https://wlr.link/welcome-rain-twitter"
        - website: "youtube"
          url: "https://wlr.link/youtube"
        - website: "instagram"
          url: "https://wlr.link/instagram"
        - website: "facebook"
          url: "https://wlr.link/facebook"
        - website: "linkedin"
          url: "https://wlr.link/linkedin"
        - website: "buymeacoffee"
          url: "https://wlr.link/buy-me-a-coffee"
        - website: "medium"
          url: "https://wlr.link/publication"
 
